name: movies
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: 0.13.3
  carousel_slider: 4.0.0
  shared_preferences: 2.0.7
  provider: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
